version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - test1
      - restore_cache:
          keys:
            - test2
      - run: docker pull gableroux/unity3d:2018.3.4f1
      - run: sudo ls /var/lib/docker
      - run: ls
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d

      - run: ls
      - run: ls /var/lib/docker
      - save_cache:
          key: test1
          paths:
            - "/var/lib/docker"
      - save_cache:
          key: test2
          paths:
            - "/project/unity3d"

      - run: |
            docker-compose ps
            docker-compose exec unity3d sh -c 'chmod +x ./ci/before_script.sh && ./ci/before_script.sh'
            docker-compose exec -e BUILD_NAME=ExampleProjectName -e BUILD_TARGET=StandaloneWindows64 unity3d sh -c 'chmod +x ./ci/build.sh && ./ci/build.sh'