defaults: &defaults
  docker:
    - image: gableroux/unity3d:2018.3.4f1
      environment:
        - BUILD_NAME: ExampleProjectName

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      BUILD_TARGET: StandaloneWindows64
    steps:
      - checkout
      - run: chmod +x ./ci/before_script.sh && ./ci/before_script.sh
      - run: chmod +x ./ci/build.sh && ./ci/build.sh
      - run: mkdir -p ./Builds/zip
      - run: zip -r "./Builds/zip/build-$BUILD_TARGET.zip" ./Builds/
      - store_artifacts:
          path: ./Builds/zip/
          
workflows:
  version: 2
  build:
    jobs:
      - build
