version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: docker volume create --name=data

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker ps
