defaults: &defaults
  working_directory: ~/optania-api
  docker:
    - image: gableroux/unity3d:2018.3.4f1
      environment:
        - BUILD_NAME: ExampleProjectName

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      BUILD_TARGET: StandaloneWindows64
    steps:
      - checkout
      - run: echo "$UNITY_LICENSE_CONTENT" | base64 --decode > /root/.local/share/unity3d/Unity/Unity_lic.ulf && chmod +x ./ci/build.sh && ./ci/build.sh
      - store_artifacts:
          path: ./Builds/
          
workflows:
  version: 2
  build:
    jobs:
      - build
