version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: docker volume create --name=data

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker-compose ps
            docker-compose exec unity3d /ci/before_script.sh
            docker-compose exec -e BUILD_NAME=ExampleProjectName -e BUILD_TARGET=StandaloneWindows64 unity3d /ci/build.sh